- name: janitor | Unarchive home data
  become: yes
  unarchive:
    src: janitor.tar.gz
    dest: /home/janitor
    owner: janitor
    group: janitor
    mode: 'u=rwX,g=,o='
  tags:
    - dc-9-users-config-janitor
    - dc-9-users-config-janitor-unarchive
    - dc-9-users-config-janitor-unarchive-home

